repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix]
      - id: ruff-format
        name: ruff (formatter)
  - repo: local
    hooks:
      - id: update-manual
        name: Update Manual
        entry: ./task generate_manual
        language: script
        files: ^.*$
        exclude: ^manual\.md$
