#!/bin/bash
set -eo pipefail

script_dir=$(dirname "$(readlink -f "$0")")


function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function generate_manual {
    uv run typer djdevx.main utils docs --output manual.md --name djdevx
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
