default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix]
      - id: ruff-format
        name: ruff (formatter)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py313-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.24.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.1"]
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.4.0
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
    - id: ripsecrets
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    - id: shellcheck
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
    - id: biome-check
      files: "\\.css$"
      exclude: "^static/css/vendor/"
