"""Shared canned model metadata for factory create tests.

These dicts mirror the JSON payload returned by ``introspect.list_models``
(i.e. Django's ``manage.py shell -c`` introspection snippet).
"""

import copy

HOME_POST = {
    "app_label": "home",
    "name": "Post",
    "fields": [
        {
            "name": "id",
            "class": "BigAutoField",
            "null": False,
            "unique": True,
            "primary_key": True,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "title",
            "class": "CharField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": 200,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "slug",
            "class": "SlugField",
            "null": False,
            "unique": True,
            "primary_key": False,
            "max_length": 200,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "body",
            "class": "TextField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "status",
            "class": "CharField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": 20,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": ["draft", "published"],
        },
        {
            "name": "is_active",
            "class": "BooleanField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "author",
            "class": "ForeignKey",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": "users.User",
            "choices": [],
        },
        {
            "name": "created_at",
            "class": "DateTimeField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": True,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "tags",
            "class": "ManyToManyField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": True,
            "one_to_one": False,
            "related": "home.Tag",
            "choices": [],
        },
    ],
}

HOME_COMMENT = {
    "app_label": "home",
    "name": "Comment",
    "fields": [
        {
            "name": "id",
            "class": "BigAutoField",
            "null": False,
            "unique": True,
            "primary_key": True,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "post",
            "class": "ForeignKey",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": "home.Post",
            "choices": [],
        },
        {
            "name": "author_email",
            "class": "EmailField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": 254,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "user",
            "class": "OneToOneField",
            "null": True,
            "unique": True,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": True,
            "related": "users.User",
            "choices": [],
        },
    ],
}

USERS_USER = {
    "app_label": "users",
    "name": "User",
    "fields": [
        {
            "name": "id",
            "class": "BigAutoField",
            "null": False,
            "unique": True,
            "primary_key": True,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "username",
            "class": "CharField",
            "null": False,
            "unique": True,
            "primary_key": False,
            "max_length": 150,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "first_name",
            "class": "CharField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": 150,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "email",
            "class": "EmailField",
            "null": False,
            "unique": True,
            "primary_key": False,
            "max_length": 254,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "password",
            "class": "CharField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": 128,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "is_active",
            "class": "BooleanField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "is_staff",
            "class": "BooleanField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "is_superuser",
            "class": "BooleanField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "last_login",
            "class": "DateTimeField",
            "null": True,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "date_joined",
            "class": "DateTimeField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": True,
            "many_to_many": False,
            "one_to_one": False,
            "related": None,
            "choices": [],
        },
        {
            "name": "groups",
            "class": "ManyToManyField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": True,
            "one_to_one": False,
            "related": "auth.Group",
            "choices": [],
        },
        {
            "name": "user_permissions",
            "class": "ManyToManyField",
            "null": False,
            "unique": False,
            "primary_key": False,
            "max_length": None,
            "auto_now": False,
            "auto_now_add": False,
            "many_to_many": True,
            "one_to_one": False,
            "related": "auth.Permission",
            "choices": [],
        },
    ],
}


def home_post() -> dict:
    return copy.deepcopy(HOME_POST)


def home_comment() -> dict:
    return copy.deepcopy(HOME_COMMENT)


def users_user() -> dict:
    return copy.deepcopy(USERS_USER)
