services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env/devcontainer
    volumes:
      - ../:/home/devuser/workspace:cached
      - precommit-cache:/home/devuser/.cache/pre-commit
    networks:
      - devcontainer
    command: sleep infinity
  db:
    image: postgres:16
    env_file:
      - ./.env/postgres
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - devcontainer
  cache:
    image: redis:7.4-alpine
    env_file:
      - ./.env/redis
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    volumes:
          - cache-data:/data
    networks:
      - devcontainer
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    env_file:
      - ./.env/pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - devcontainer
    depends_on:
      - db

volumes:
  app-db-data:
    driver: local
  precommit-cache:
    driver: local
  pgadmin-data:
    driver: local
  pgadmin-config:
    driver: local
  cache-data:
    driver: local

networks:
  devcontainer:
    driver: bridge
