from settings.django.base import INSTALLED_APPS, MIDDLEWARE
from settings.utils.env import get_env


INSTALLED_APPS += [
    "defender",
]

MIDDLEWARE += [
    "defender.middleware.FailedLoginMiddleware",
]

env = get_env()

DEFENDER_LOGIN_FAILURE_LIMIT = env("DEFENDER_LOGIN_FAILURE_LIMIT", default=3)
DEFENDER_LOGIN_FAILURE_LIMIT_USERNAME = env(
    "DEFENDER_LOGIN_FAILURE_LIMIT_USERNAME", default=DEFENDER_LOGIN_FAILURE_LIMIT
)
DEFENDER_LOGIN_FAILURE_LIMIT_IP = env(
    "DEFENDER_LOGIN_FAILURE_LIMIT_IP", default=DEFENDER_LOGIN_FAILURE_LIMIT
)
DEFENDER_BEHIND_REVERSE_PROXY = env("DEFENDER_BEHIND_REVERSE_PROXY", default=False)
DEFENDER_REVERSE_PROXY_HEADER = env(
    "DEFENDER_REVERSE_PROXY_HEADER", default="HTTP_X_FORWARDED_FOR"
)
DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME = env(
    "DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME", default=False
)
DEFENDER_DISABLE_IP_LOCKOUT = env("DEFENDER_DISABLE_IP_LOCKOUT", default=False)
DEFENDER_DISABLE_USERNAME_LOCKOUT = env(
    "DEFENDER_DISABLE_USERNAME_LOCKOUT", default=False
)
DEFENDER_COOLOFF_TIME = env("DEFENDER_COOLOFF_TIME", default=300)
DEFENDER_ATTEMPT_COOLOFF_TIME = env(
    "DEFENDER_ATTEMPT_COOLOFF_TIME", default=DEFENDER_COOLOFF_TIME
)
DEFENDER_LOCKOUT_COOLOFF_TIME = env(
    "DEFENDER_LOCKOUT_COOLOFF_TIME", default=DEFENDER_COOLOFF_TIME
)
DEFENDER_LOCKOUT_TEMPLATE = env("DEFENDER_LOCKOUT_TEMPLATE", default=None)
DEFENDER_USERNAME_FORM_FIELD = env("DEFENDER_USERNAME_FORM_FIELD", default="username")
DEFENDER_CACHE_PREFIX = env("DEFENDER_CACHE_PREFIX", default="defender")
DEFENDER_LOCKOUT_URL = env("DEFENDER_LOCKOUT_URL", default=None)
DEFENDER_REDIS_URL = env("DEFENDER_REDIS_URL", default="redis://localhost:6379/0")
DEFENDER_REDIS_PASSWORD_QUOTE = env("DEFENDER_REDIS_PASSWORD_QUOTE", default=False)
DEFENDER_REDIS_NAME = env("DEFENDER_REDIS_NAME", default=None)
DEFENDER_STORE_ACCESS_ATTEMPTS = env("DEFENDER_STORE_ACCESS_ATTEMPTS", default=True)
DEFENDER_USE_CELERY = env("DEFENDER_USE_CELERY", default=False)
DEFENDER_ACCESS_ATTEMPT_EXPIRATION = env(
    "DEFENDER_ACCESS_ATTEMPT_EXPIRATION", default=24
)
DEFENDER_GET_USERNAME_FROM_REQUEST_PATH = env(
    "DEFENDER_GET_USERNAME_FROM_REQUEST_PATH",
    default="defender.utils.username_from_request",
)
