FROM python:{{ python_version }}-slim AS base

FROM base AS static_builds

WORKDIR /app

RUN apt-get update && apt-get install gettext -y

ADD . /app

RUN --mount=type=cache,target=/root/.cache/pixi \
    curl -fsSL https://pixi.sh/install.sh | sh && \
    mkdir -p /app/locale/ && \
    pixi run manage.py collectstatic --noinput && \
    pixi run manage.py compilemessages

FROM base AS builder

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pixi \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=pixi.lock,target=pixi.lock \
    curl -fsSL https://pixi.sh/install.sh | sh && \
    pixi install --frozen

FROM base AS source

WORKDIR /app

COPY . /app/
RUN rm -rf staticfiles/src docker pyproject.toml pixi.lock

FROM base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
ENV PATH=/app/.pixi/envs/default/bin/:$PATH

EXPOSE 8000

ARG USERNAME=django
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}

WORKDIR /app

COPY --from=source --chown=${USERNAME}:${USERNAME} /app /app/
COPY --from=builder --chown=${USERNAME}:${USERNAME} /app/.pixi/ /app/.pixi
COPY --from=static_builds --chown=${USERNAME}:${USERNAME} /app/staticfiles/ /app/staticfiles/
COPY --from=static_builds --chown=${USERNAME}:${USERNAME} /app/locale /app/locale/
COPY --chown=${USERNAME}:${USERNAME} docker/entrypoint.sh /app/

RUN chmod +x /app/entrypoint.sh

USER ${USERNAME}

ENTRYPOINT ["/bin/bash", "-euo", "pipefail", "/app/entrypoint.sh"]
