FROM python:{{ python_version }}-slim-trixie

ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    mkdir -p /home/devuser/.config/ /home/devuser/.bashrc.d && \
    chown -R $USERNAME:$USERNAME /home/devuser/.config /home/devuser/.bashrc.d

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update && apt-get install -y --no-install-recommends \
    locales \
    git \
    build-essential \
    curl \
    lsd && \
    sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

USER $USERNAME
WORKDIR /home/devuser/workspace

COPY --chown=$USERNAME:$USERNAME bashrc.d/* /home/devuser/.bashrc.d/
COPY config/git/config /etc/gitconfig
COPY --chown=$USERNAME:$USERNAME config/.config/* /home/devuser/.config/
RUN echo 'for f in ~/.bashrc.d/*; do source $f; done' >> /home/devuser/.bashrc

RUN curl -fsSL https://pixi.sh/install.sh | sh && \
    curl -fsSL https://opencode.ai/install | bash

RUN /home/devuser/.pixi/bin/pixi global install coreutils \
    vim \
    less \
    bat \
    gettext \
    tree \
    jq \
    yq \
    starship \
    ripgrep \
    git-delta \
    fd-find \
    fzf \
    bash-completion \
    shellcheck \
    wget \
    gh \
    biome \
    herdr \
    graphifyy \
    less \
    uv

RUN /home/devuser/.pixi/bin/uv tool install git+https://github.com/siavashoutadi/djdevx
