services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEVCONTAINER: "true"
      PYTHONBREAKPOINT: "ipdb.set_trace"
    volumes:
    - ../:/home/devuser/workspace:cached
    - prek-cache:/home/devuser/.cache/prek
    networks:
    - devcontainer
    command: sleep infinity
volumes:
  prek-cache:
    driver: local
networks:
  devcontainer:
    driver: bridge
